sudo: required # Added only to join beta (https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/)
dist: trusty

language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7

notifications:
  email: false
