sudo: required # Added only to join beta (https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/)
dist: trusty

language: java

jdk:
  - oraclejdk8
  # oraclejdk7 is not available anymore (https://github.com/travis-ci/travis-ci/issues/7884)
  - openjdk8
  - openjdk7

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master

notifications:
  email: false
